name = "Mudie"
uuid = "4d8691f9-d7cd-4649-8446-b9e4aa9b174c"
version = "1.0.0-DEV"
authors = ["DIE"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
StringEncodings = "69024149-9ee7-55f6-a4c4-859efe599b68"

[compat]
Dates = "1.11.0"
Documenter = "1.15.0"
Makie = "0.24.6"
StringEncodings = "0.3.7"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
